GNU Octave: /home/manpreet/OCTAVE_WORK/class.cc File Reference
class.cc File Reference
#include <iostream>
Classes
class top
class middle
class bottom
Functions
int main ()
Function Documentation
int main ()
Definition at line 45 of file class.cc.
References bottom::cube(), top::getdata(), and top::putdata().
 {
 //clrscr();
 bottom b1;
 b1.getdata();
 b1.cube();
 b1.putdata();
 return 0;
 }